"""table name change

Revision ID: 2c93a05dcd94
Revises: 06eafbd255ad
Create Date: 2026-03-26 13:26:45.168525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c93a05dcd94'
down_revision: Union[str, Sequence[str], None] = '06eafbd255ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product descriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_sku', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], name=op.f('product descriptions_product_sku_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product descriptions_pkey'))
    )
    op.drop_table('product_descriptions')
    # ### end Alembic commands ###
