"""Changes for the structure for table |products|

Revision ID: 602d70b93abe
Revises: 8fa3d33773ae
Create Date: 2026-03-19 18:17:14.670612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '602d70b93abe'
down_revision: Union[str, Sequence[str], None] = '8fa3d33773ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vat_enum') THEN "
        "CREATE TYPE vat_enum AS ENUM ('FULL', 'REDUCED', 'FREE', 'NONE'); "
        "END IF; "
        "END $$;"
    )
    op.execute(
        'ALTER TABLE "product descriptions" '
        'DROP CONSTRAINT IF EXISTS "product descriptions_product_sku_fkey"'
    )
    op.alter_column(
        "product descriptions",
        "product_sku",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using='"product_sku"::varchar',
        existing_nullable=False,
    )
    op.alter_column('products', 'sku',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               server_default=None,
               postgresql_using='"sku"::varchar',
               existing_nullable=False)
    op.alter_column('products', 'ean',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('products', 'vat',
               existing_type=postgresql.ENUM('FULL', 'REDUCED', 'FREE', 'NONE', name='vatenum'),
               type_=sa.Enum('FULL', 'REDUCED', 'FREE', 'NONE', name='vat_enum'),
               postgresql_using='"vat"::text::vat_enum',
               existing_nullable=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_unique_constraint(None, 'products', ['sku'])
    op.execute(
        'ALTER TABLE "product descriptions" '
        'ADD CONSTRAINT "product descriptions_product_sku_fkey" '
        'FOREIGN KEY (product_sku) REFERENCES products (sku)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vatenum') THEN "
        "CREATE TYPE vatenum AS ENUM ('FULL', 'REDUCED', 'FREE', 'NONE'); "
        "END IF; "
        "END $$;"
    )
    op.execute(
        'ALTER TABLE "product descriptions" '
        'DROP CONSTRAINT IF EXISTS "product descriptions_product_sku_fkey"'
    )
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.alter_column('products', 'vat',
               existing_type=sa.Enum('FULL', 'REDUCED', 'FREE', 'NONE', name='vat_enum'),
               type_=postgresql.ENUM('FULL', 'REDUCED', 'FREE', 'NONE', name='vatenum'),
               postgresql_using='"vat"::text::vatenum',
               existing_nullable=False)
    op.alter_column('products', 'ean',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               postgresql_using='"ean"::integer',
               existing_nullable=False)
    op.alter_column('products', 'sku',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               postgresql_using='"sku"::integer',
               existing_nullable=False)
    op.alter_column(
        "product descriptions",
        "product_sku",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using='"product_sku"::integer',
        existing_nullable=False,
    )
    op.execute(
        'ALTER TABLE "product descriptions" '
        'ADD CONSTRAINT "product descriptions_product_sku_fkey" '
        'FOREIGN KEY (product_sku) REFERENCES products (sku)'
    )
    # ### end Alembic commands ###
