"""Changed products table's primary key

Revision ID: 8fa3d33773ae
Revises: f5a7eafdc268
Create Date: 2026-03-19 18:11:07.585215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa3d33773ae'
down_revision: Union[str, Sequence[str], None] = 'f5a7eafdc268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'id')
    # ### end Alembic commands ###
