"""update constraint for table factories

Revision ID: 96d979a027de
Revises: a2ed222ba93f
Create Date: 2026-05-25 13:09:28.367017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d979a027de'
down_revision: Union[str, Sequence[str], None] = 'a2ed222ba93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('factories_name_key'), 'factories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('factories_name_key'), 'factories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
