"""Init

Revision ID: a614c882e48c
Revises: 
Create Date: 2026-03-27 13:10:47.199915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a614c882e48c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('account_source', sa.String(length=20), nullable=False),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('pricing', sa.Float(), nullable=False),
    sa.Column('vat', sa.Enum('FULL', 'REDUCED', 'FREE', 'NONE', name='vat_enum'), nullable=False),
    sa.Column('productReference', sa.String(), nullable=True),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('productLine', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('bullet_points', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_products_sku')
    )
    op.create_table('product_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_descriptions')
    op.drop_table('products')
    # ### end Alembic commands ###
