"""User roles table add

Revision ID: bcfc57f81f9e
Revises: 8d9a7c61c2b1
Create Date: 2026-04-02 15:40:33.513628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfc57f81f9e'
down_revision: Union[str, Sequence[str], None] = '8d9a7c61c2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SEO', 'EMPLOYEE', name='role_enum'), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_sku', 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sku', 'products', type_='unique')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
