"""update factories table

Revision ID: e8ceb87e7be8
Revises: 4e81d98ae87f
Create Date: 2026-05-25 12:36:40.206399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e8ceb87e7be8"
down_revision: Union[str, Sequence[str], None] = "4e81d98ae87f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factories", sa.Column("account", sa.String(), nullable=False))
    op.drop_index(
        op.f("ix_product_descriptions_non_empty_description_sku"),
        table_name="product_descriptions",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_product_descriptions_product_sku_name"),
        table_name="product_descriptions",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_products_product_category"),
        table_name="products",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_products_product_category_normalized"),
        table_name="products",
        if_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_product_category_normalized"),
        "products",
        [sa.literal_column("lower(btrim(product_category::text))")],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_product_category"),
        "products",
        ["product_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_descriptions_product_sku_name"),
        "product_descriptions",
        ["product_sku", "name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_descriptions_non_empty_description_sku"),
        "product_descriptions",
        ["product_sku"],
        unique=False,
        postgresql_where="(((name)::text = 'description'::text) AND (length(btrim((value)::text)) > 0))",
    )
    op.drop_column("factories", "account")
    # ### end Alembic commands ###
