"""variation_theme_added_table

Revision ID: f187c05e21e8
Revises: 80daaf6b5c1a
Create Date: 2026-06-09 15:42:32.704812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f187c05e21e8"
down_revision: Union[str, Sequence[str], None] = "80daaf6b5c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variation_themes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("attribute_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["category_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.alter_column('attributes', 'group_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    op.drop_constraint(op.f("attributes_name_key"), "attributes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("attributes_name_key"), "attributes", ["name"])
    # op.alter_column('attributes', 'group_id',
    #            existing_type=sa.String(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    op.drop_table("variation_themes")
    # ### end Alembic commands ###
