"""init

Revision ID: f5a7eafdc268
Revises: 
Create Date: 2026-03-19 18:04:16.999547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5a7eafdc268'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('ean', sa.Integer(), nullable=False),
    sa.Column('pricing', sa.Integer(), nullable=False),
    sa.Column('vat', sa.Enum('FULL', 'REDUCED', 'FREE', 'NONE', name='vatenum'), nullable=False),
    sa.Column('productReference', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('productLine', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bullet_points', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('product descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product descriptions')
    op.drop_table('products')
    # ### end Alembic commands ###
