"""test

Revision ID: f6b6e9ddec37
Revises: 20260624120000
Create Date: 2026-06-26 16:22:56.548982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6b6e9ddec37"
down_revision: Union[str, Sequence[str], None] = "20260624120000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translation_cache")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_cache",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("original_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("translated_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "source_lang", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "target_lang", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "provider",
            sa.VARCHAR(length=30),
            server_default=sa.text("'deepl'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("context", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("translation_cache_pkey")),
        sa.UniqueConstraint(
            "original_text",
            "source_lang",
            "target_lang",
            "provider",
            "context",
            name=op.f("uq_translation_cache_lookup"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
